# Generated by Django 4.2 on 2023-04-19 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practitionerCareV1Api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment_Dates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.CharField(max_length=5)),
                ('tuesday', models.CharField(max_length=5)),
                ('wednesday', models.CharField(max_length=5)),
                ('thursday', models.CharField(max_length=5)),
                ('friday', models.CharField(max_length=5)),
                ('saturday', models.CharField(max_length=5)),
                ('sunday', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Dentist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='the dentist first name')),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('practice', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('useful_information', models.CharField(max_length=500)),
                ('means_of_payment', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='the hospital name')),
                ('address', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name='the user first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
